# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Benfield Brass
email:
description: >- # this means to ignore newlines until "baseurl:"
  The Benfield Brass Band is a non-profit volunteer organization which performs a number of concerts annually in the Annapolis/Baltimore area, as well as at the annual Gettysburg Brass Band Festival held in June each year in Gettysburg, PA. Many of the band members play together in other local instrumental groups, and the band has several family members playing. The band comes together in the fall and plays through midsummer.
  The band was formed in 1998 to attend the first Gettysburg Brass Band Festival and we have performed there nearly every year since. The main purpose of the band is to provide the opportunity for brass players in the area to experience playing in a British Style brass band. Over the years the band has gradually grown in size and skill. The band has reached a size pretty close to the limit, but we continue to improve the quality of our playing. BBB is not a contesting band which allows us to grow our membership beyond the typical contesting sized British band.
twitter_username: username
github_username: benfieldbrass
repository: benfieldbrass/benfieldbrass.github.io
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

future: true
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Benfield Brass"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Annapolis MD"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://benfieldbrass.github.io/ "
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-f"
      url: "https://www.facebook.com/p/Benfield-Brass-Band-100055208095368/"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://benfieldbrass.github.io/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-f"
      url: "https://www.facebook.com/p/Benfield-Brass-Band-100055208095368/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
